// packages/feature_base/moodiary_editor/editor/src/ui/overlay/WheelColumn.tsx
import { useImperativeHandle, useRef, type Ref } from 'react'

const ITEM = 40

export interface WheelColumnHandle {
  scrollTo(index: number): void
  current(): number
}

export default function WheelColumn({
  ref,
  items,
  label,
  className,
}: {
  ref?: Ref<WheelColumnHandle>
  items: string[]
  label: string
  className?: string
}) {
  const list = useRef<HTMLDivElement>(null)

  useImperativeHandle(
    ref,
    () => ({
      scrollTo: (index) => {
        if (list.current) list.current.scrollTop = index * ITEM
      },
      current: () => {
        const top = list.current?.scrollTop ?? 0
        return Math.min(items.length - 1, Math.max(0, Math.round(top / ITEM)))
      },
    }),
    [items.length],
  )

  return (
    <div className={`moodiary-wheel${className ? ` ${className}` : ''}`}>
      <div className="moodiary-wheel__band" aria-hidden="true"></div>
      <div ref={list} className="moodiary-wheel__list" role="listbox" aria-label={label} tabIndex={-1}>
        {items.map((item, i) => (
          <div
            key={i}
            className="moodiary-wheel__item"
            onClick={() => list.current?.scrollTo({ top: i * ITEM, behavior: 'smooth' })}
          >
            {item}
          </div>
        ))}
      </div>
    </div>
  )
}

// packages/feature_base/moodiary_editor/editor/src/components/ui/WheelColumn.vue
<script setup lang="ts">
import { ref } from 'vue'

const ITEM = 40

const props = defineProps<{
  items: string[]
  label: string
}>()

const list = ref<HTMLElement>()

function scrollTo(index: number): void {
  if (list.value) list.value.scrollTop = index * ITEM
}

function current(): number {
  const top = list.value?.scrollTop ?? 0
  return Math.min(props.items.length - 1, Math.max(0, Math.round(top / ITEM)))
}

defineExpose({ scrollTo, current })
</script>

<template>
  <div class="moodiary-wheel">
    <div class="moodiary-wheel__band" aria-hidden="true"></div>
    <div ref="list" class="moodiary-wheel__list" role="listbox" :aria-label="label" tabindex="-1">
      <div v-for="(item, i) in items" :key="i" class="moodiary-wheel__item" @click="list?.scrollTo({ top: i * ITEM, behavior: 'smooth' })">
        {{ item }}
      </div>
    </div>
  </div>
</template>
