// packages/feature_base/moodiary_editor/editor/src/ui/nodes/AudioNodeView.tsx
import { useEffect, useRef, useState } from 'react'
import { NodeViewWrapper, type NodeViewProps } from '@tiptap/react'
import { Pause, Play, Volume2, VolumeX } from 'lucide-react'
import { cn } from 'cn'
import BlockHandle from './BlockHandle'
import { fetchMediaName, mediaUrl } from '@/core/editor/media'
import { formatTime, useMediaControls } from '@/ui/hooks/use-media'
import { t } from '@/core/i18n'
import { useBlockMenu } from '@/ui/hooks/use-block-menu'
import { rangeClass } from '@/lib/range'
import { Button } from '@/ui/primitives/button'

export default function AudioNodeView({ node, selected, getPos }: NodeViewProps) {
  const { canEdit, menuOpen, openMenu } = useBlockMenu('audio', getPos)

  const filename = (node.attrs.filename as string | null) ?? ''
  const src = filename ? mediaUrl(filename) : undefined

  const [fetchedName, setFetchedName] = useState<string | null>(null)
  useEffect(() => {
    if (!filename) return
    let alive = true
    void fetchMediaName(filename).then((name) => {
      if (alive && name) setFetchedName(name)
    })
    return () => {
      alive = false
    }
  }, [filename])
  const displayName = fetchedName ?? t('audio.defaultName')

  const audioRef = useRef<HTMLAudioElement>(null)
  const { playing, duration, muted, sliderValue, toggle, toggleMute, seekTo, endSeek } =
    useMediaControls(audioRef)

  return (
    <NodeViewWrapper
      className={`moodiary-media moodiary-media--audio${selected ? ' is-selected' : ''}${menuOpen ? ' is-menu-open' : ''}`}
      contentEditable={false}
    >
      <div className="moodiary-block__body flex items-center gap-3 rounded-lg border border-border bg-muted px-3 py-2.5">
        <Button
          variant="default"
          size="icon"
          className="shrink-0 rounded-full"
          type="button"
          title={playing ? t('audio.pause') : t('audio.play')}
          onMouseDown={(e) => e.preventDefault()}
          onClick={toggle}
        >
          {playing ? <Pause className="size-5" /> : <Play className="size-5" />}
        </Button>
        <div className="flex min-w-0 flex-1 flex-col gap-1">
          <div className="flex items-center gap-2">
            <span className="min-w-0 flex-1 truncate text-sm font-medium">{displayName}</span>
            <Button
              variant="ghost"
              size="icon-xs"
              className="shrink-0 rounded-full"
              type="button"
              title={muted ? t('audio.unmute') : t('audio.mute')}
              onMouseDown={(e) => e.preventDefault()}
              onClick={toggleMute}
            >
              {muted ? <VolumeX className="size-4" /> : <Volume2 className="size-4" />}
            </Button>
            {canEdit && (
              <BlockHandle variant="inline" onOpen={openMenu} />
            )}
          </div>
          <div className="flex items-center gap-2">
            <input
              className={cn(rangeClass, 'h-1.5 flex-1')}
              type="range"
              min={0}
              max={duration || 0}
              step="any"
              value={sliderValue}
              aria-label={t('audio.progressLabel')}
              onChange={(e) => seekTo(Number(e.currentTarget.value))}
              onPointerUp={(e) => endSeek(Number(e.currentTarget.value))}
              onPointerCancel={(e) => endSeek(Number(e.currentTarget.value))}
              onKeyUp={(e) => endSeek(Number(e.currentTarget.value))}
            />
            <span className="shrink-0 text-xs text-muted-foreground tabular-nums">
              {formatTime(sliderValue)} / {formatTime(duration)}
            </span>
          </div>
        </div>
      </div>
      <audio ref={audioRef} src={src} preload="metadata" />
    </NodeViewWrapper>
  )
}

// packages/feature/moodiary_editor/editor/src/components/nodes/AudioNodeView.vue
<script setup lang="ts">
// 音频节点视图：webview 内播放，用原生 <audio>（HTMLMediaElement API）+ daisyUI 自绘控件（无播放器库）。
// 音频字节由本地回环服务按需供给（支持 HTTP Range）。控件：播放/暂停 + daisyUI range 进度条（自带
// 已播放填充）+ 时间 + 静音。图标用 unplugin-icons 按需引入 lucide。读模式下同样可播。
import { computed, ref } from 'vue'
import { NodeViewWrapper, nodeViewProps } from '@tiptap/vue-3'
import IconPlay from '~icons/lucide/play'
import IconPause from '~icons/lucide/pause'
import IconVolume from '~icons/lucide/volume-2'
import IconMuted from '~icons/lucide/volume-x'
import { mediaUrl } from '../../editor/media'
import { formatTime, useMediaControls } from '../../editor/use-media'

const props = defineProps(nodeViewProps)

const filename = computed(() => (props.node.attrs.filename as string | null) ?? '')
const src = computed(() => (filename.value ? mediaUrl(filename.value) : ''))

const audioEl = ref<HTMLAudioElement | null>(null)
const { playing, duration, muted, sliderValue, toggle, toggleMute, onSeekInput, onSeekChange } =
  useMediaControls(audioEl)
</script>

<template>
  <NodeViewWrapper
    class="moodiary-media moodiary-media--audio"
    :class="{ 'is-selected': selected }"
    contenteditable="false"
  >
    <div
      class="flex items-center gap-3 rounded-box border border-base-300 bg-base-200 px-3 py-2"
    >
      <button
        class="btn btn-circle btn-sm btn-primary shrink-0"
        type="button"
        :title="playing ? '暂停' : '播放'"
        @click="toggle"
      >
        <component :is="playing ? IconPause : IconPlay" class="size-5" />
      </button>
      <input
        class="range range-primary range-xs flex-1"
        type="range"
        min="0"
        :max="duration || 0"
        step="any"
        :value="sliderValue"
        aria-label="音频进度"
        @input="onSeekInput"
        @change="onSeekChange"
      />
      <span class="shrink-0 text-xs tabular-nums opacity-70">
        {{ formatTime(sliderValue) }} / {{ formatTime(duration) }}
      </span>
      <button
        class="btn btn-circle btn-ghost btn-xs shrink-0"
        type="button"
        :title="muted ? '取消静音' : '静音'"
        @click="toggleMute"
      >
        <component :is="muted ? IconMuted : IconVolume" class="size-5" />
      </button>
    </div>
    <audio ref="audioEl" :src="src" preload="metadata"></audio>
  </NodeViewWrapper>
</template>
