// packages/feature_base/moodiary_editor/editor/src/components/PopupMenu.vue
<script setup lang="ts">
import { computed, ref, watch, type Component } from 'vue'
import IconCheck from '~icons/lucide/check'
import Popover from './ui/Popover.vue'

export interface PopupMenuItem {
  key: string
  label: string
  icon?: Component
  active: boolean
  destructive?: boolean
}

const props = withDefaults(
  defineProps<{
    items?: PopupMenuItem[]
    modelValue: boolean
  }>(),
  { items: () => [] },
)

const emit = defineEmits<{
  (e: 'update:modelValue', value: boolean): void
  (e: 'select', key: string): void
}>()

const triggerRef = ref<HTMLElement>()
const pop = ref<InstanceType<typeof Popover>>()

const hasIcon = computed(() => props.items.some((item) => item.icon != null))
const hasActive = computed(() => props.items.some((item) => item.active))

function onSelect(key: string): void {
  emit('select', key)
  emit('update:modelValue', false)
}

watch(
  () => props.modelValue,
  (open) => {
    if (open && triggerRef.value) pop.value?.open(triggerRef.value)
    else pop.value?.close()
  },
)
</script>

<template>
  <div class="popup-menu-host">
    <div ref="triggerRef" @click="emit('update:modelValue', !modelValue)">
      <slot name="trigger" />
    </div>
    <Popover ref="pop" keep-focus panel-class="min-w-42 max-w-80" @closed="emit('update:modelValue', false)">
      <button
        v-for="item in items"
        :key="item.key"
        type="button"
        class="moodiary-pop-item"
        :class="{ 'is-active': item.active, 'is-danger': item.destructive }"
        @click.stop="onSelect(item.key)"
      >
        <span v-if="hasIcon" class="flex w-5 shrink-0 justify-center">
          <component :is="item.icon" v-if="item.icon" class="size-[19px]" />
        </span>
        <span class="flex-1 whitespace-nowrap">{{ item.label }}</span>
        <span v-if="hasActive" class="flex w-[18px] shrink-0 justify-center">
          <IconCheck v-if="item.active" class="size-[18px]" />
        </span>
      </button>
    </Popover>
  </div>
</template>

// packages/feature_base/moodiary_editor/editor/src/ui/overlay/PopupMenu.tsx
import { useEffect, useRef, type ComponentType, type ReactNode } from 'react'
import { Check } from 'lucide-react'
import Popover, { type PopoverHandle } from './Popover'

export interface PopupMenuItem {
  key: string
  label: string
  icon?: ComponentType<{ className?: string }>
  active: boolean
  destructive?: boolean
}

export default function PopupMenu({
  items = [],
  open,
  onOpenChange,
  onSelect,
  children,
}: {
  items?: PopupMenuItem[]
  open: boolean
  onOpenChange: (open: boolean) => void
  onSelect: (key: string) => void
  children?: ReactNode
}) {
  const trigger = useRef<HTMLDivElement>(null)
  const pop = useRef<PopoverHandle>(null)
  const hasIcon = items.some((item) => item.icon != null)
  const hasActive = items.some((item) => item.active)

  useEffect(() => {
    if (open && trigger.current) pop.current?.open(trigger.current)
    else pop.current?.close()
  }, [open])

  return (
    <div className="popup-menu-host">
      <div ref={trigger} onClick={() => onOpenChange(!open)}>
        {children}
      </div>
      <Popover
        ref={pop}
        keepFocus
        panelClass="min-w-42 max-w-80"
        onClosed={() => onOpenChange(false)}
      >
        {items.map((item) => {
          const Icon = item.icon
          return (
            <button
              key={item.key}
              type="button"
              className={`moodiary-pop-item${item.active ? ' is-active' : ''}${item.destructive ? ' is-danger' : ''}`}
              onClick={(e) => {
                e.stopPropagation()
                onSelect(item.key)
                onOpenChange(false)
              }}
            >
              {hasIcon && (
                <span className="flex w-5 shrink-0 justify-center">
                  {Icon && <Icon className="size-[19px]" />}
                </span>
              )}
              <span className="flex-1 whitespace-nowrap">{item.label}</span>
              {hasActive && (
                <span className="flex w-[18px] shrink-0 justify-center">
                  {item.active && <Check className="size-[18px]" />}
                </span>
              )}
            </button>
          )
        })}
      </Popover>
    </div>
  )
}
