// packages/feature_base/moodiary_editor/editor/src/components/MoodiaryEditor.tsx
import { useCallback, useEffect, useLayoutEffect, useRef, useState } from 'react'
import { NodeSelection, type Transaction } from '@tiptap/pm/state'
import { EditorContent, useEditor } from '@tiptap/react'
import { createEditorKit } from '../editor/tiptap'
import { bindApi, emitChange, markReady } from '../bridge'
import { post } from '../bridge/post'
import { links as linksStore, meta as metaStore } from '../bridge/meta'
import { bindScrollViewport } from '../bridge/scroll'
import { registerTitleFocus, title as titleStore } from '../bridge/title'
import EditorToolbar, { type PickType } from './EditorToolbar'
import EditorSearchBar from './EditorSearchBar'
import EditorMetaHeader from './EditorMetaHeader'
import EditorLinksPanel from './EditorLinksPanel'
import BlockMenu from './block/BlockMenu'
import UndoToast from './ui/UndoToast'
import { editable as editableStore } from '../editor/editable'
import { dismissKeyboard } from '../editor/keyboard'
import { openSearch } from '../editor/search'
import { useT } from '../i18n'
import { useStore } from '../lib/store'
import { wordCountOf } from '../editor/word-count'

export default function MoodiaryEditor({
  editable: initialEditable,
  platform,
}: {
  editable: boolean
  platform: 'mobile' | 'desktop'
}) {
  const t = useT()
  const editable = useStore(editableStore)
  const meta = useStore(metaStore)
  const links = useStore(linksStore)
  const title = useStore(titleStore)

  const [kit] = useState(() =>
    createEditorKit({ editable: initialEditable, placeholder: t('content'), onChange: emitChange }),
  )
  const [options] = useState(() => ({ ...kit.options, immediatelyRender: true as const }))
  const editor = useEditor(options)

  const [wordCount, setWordCount] = useState(0)
  const titleEl = useRef<HTMLTextAreaElement>(null)
  const viewportEl = useRef<HTMLDivElement>(null)
  const titleComposing = useRef(false)
  const activeHeadingIndex = useRef(-1)
  const spyRaf = useRef(0)
  const scrollRaf = useRef(0)
  const viewportBottom = useRef(Infinity)

  const computeActiveHeading = useCallback((): void => {
    const vp = viewportEl.current
    if (!vp) return
    const heads = vp.querySelectorAll<HTMLElement>(
      '.ProseMirror h1, .ProseMirror h2, .ProseMirror h3, .ProseMirror h4, .ProseMirror h5, .ProseMirror h6',
    )
    const vpTop = vp.getBoundingClientRect().top
    let active = heads.length > 0 ? 0 : -1
    heads.forEach((h, i) => {
      if (h.getBoundingClientRect().top - vpTop <= 12) active = i
    })
    if (active !== activeHeadingIndex.current) {
      activeHeadingIndex.current = active
      post('activeHeading', active)
    }
  }, [])
  const onViewportScroll = useCallback((): void => {
    cancelAnimationFrame(spyRaf.current)
    spyRaf.current = requestAnimationFrame(computeActiveHeading)
  }, [computeActiveHeading])

  useEffect(() => {
    kit.attach(editor)
    bindApi(kit.api)
    markReady()
    setWordCount(wordCountOf(editor.state.doc))
    const onTx = ({ transaction }: { transaction: Transaction }): void => {
      onViewportScroll()
      if (transaction.docChanged && !editableStore.get()) setWordCount(wordCountOf(editor.state.doc))
    }
    editor.on('transaction', onTx)
    return () => {
      editor.off('transaction', onTx)
    }
  }, [editor, kit, onViewportScroll])

  useEffect(() => {
    if (!editable) setWordCount(wordCountOf(editor.state.doc))
  }, [editable, editor])

  const titleVisible = editable || title.trim().length > 0
  const autoGrowTitle = useCallback((): void => {
    const el = titleEl.current
    // 隐藏时 scrollHeight 恒为 0，量出来会把 height 钉死成 0px
    if (!el || el.offsetParent === null) return
    el.style.height = 'auto'
    el.style.height = `${el.scrollHeight}px`
  }, [])
  useLayoutEffect(() => {
    const el = titleEl.current
    if (el && el.value !== title) el.value = title
    autoGrowTitle()
  }, [title, titleVisible, autoGrowTitle])

  function onTitleInput(e: React.FormEvent<HTMLTextAreaElement>): void {
    const el = e.currentTarget
    titleStore.set(el.value)
    autoGrowTitle()
    if (titleComposing.current) return
    post('titleChange', el.value)
  }
  function onTitleCompositionEnd(e: React.CompositionEvent<HTMLTextAreaElement>): void {
    titleComposing.current = false
    const el = e.currentTarget
    titleStore.set(el.value)
    post('titleChange', el.value)
  }
  function onTitleKeydown(e: React.KeyboardEvent<HTMLTextAreaElement>): void {
    if (e.key !== 'Enter' || e.nativeEvent.isComposing) return
    e.preventDefault()
    editor.commands.focus('start')
  }

  const pick = useCallback((type: PickType): void => {
    dismissKeyboard()
    post(type)
  }, [])

  useEffect(() => {
    const vp = viewportEl.current
    registerTitleFocus(() => titleEl.current?.focus())
    bindScrollViewport(vp)
    vp?.addEventListener('scroll', onViewportScroll, { passive: true })
    viewportBottom.current = vp?.getBoundingClientRect().bottom ?? Infinity
    const onViewportResize = (): void => {
      const box = viewportEl.current
      if (!box) return
      const bounds = box.getBoundingClientRect()
      const bottomBefore = viewportBottom.current
      viewportBottom.current = bounds.bottom
      if (!editor.isEditable || !editor.isFocused) return
      const { selection } = editor.state
      const caret = editor.view.coordsAtPos(
        selection instanceof NodeSelection ? selection.from : selection.head,
      )
      if (caret.bottom < bounds.top || caret.top > bottomBefore) return
      cancelAnimationFrame(scrollRaf.current)
      scrollRaf.current = requestAnimationFrame(() => editor.commands.scrollIntoView())
    }
    const onKeydown = (e: KeyboardEvent): void => {
      if ((e.metaKey || e.ctrlKey) && (e.key === 'f' || e.key === 'F')) {
        if (!editableStore.get()) return
        e.preventDefault()
        openSearch()
      }
    }
    if (platform === 'mobile') window.addEventListener('resize', onViewportResize)
    window.addEventListener('keydown', onKeydown)
    return () => {
      registerTitleFocus(null)
      bindScrollViewport(null)
      vp?.removeEventListener('scroll', onViewportScroll)
      window.removeEventListener('resize', onViewportResize)
      window.removeEventListener('keydown', onKeydown)
      cancelAnimationFrame(scrollRaf.current)
      cancelAnimationFrame(spyRaf.current)
    }
  }, [editor, platform, onViewportScroll])

  const showLinks =
    !editable && links != null && links.outgoing.length + links.incoming.length > 0

  return (
    <div className="moodiary-editor-root" data-platform={platform}>
      {editable && platform === 'desktop' && (
        <EditorToolbar editor={editor} platform={platform} onPick={pick} />
      )}
      {platform === 'desktop' && <EditorSearchBar platform={platform} />}
      <div className="moodiary-editor-scroll">
        <div ref={viewportEl} className="moodiary-editor-viewport">
          {meta && <EditorMetaHeader meta={meta} editable={editable} wordCount={wordCount} />}
          <textarea
            ref={titleEl}
            className="moodiary-title"
            style={titleVisible ? undefined : { display: 'none' }}
            rows={1}
            readOnly={!editable}
            placeholder={editable ? t('titlePlaceholder') : ''}
            onInput={onTitleInput}
            onCompositionStart={() => {
              titleComposing.current = true
            }}
            onCompositionEnd={onTitleCompositionEnd}
            onKeyDown={onTitleKeydown}
            onFocus={() => post('focusChange', 'title')}
            onBlur={() => post('focusChange', '')}
          />
          <EditorContent editor={editor} className="moodiary-editor" />
          {showLinks && links && <EditorLinksPanel links={links} />}
        </div>
      </div>
      {platform === 'mobile' && <EditorSearchBar platform={platform} />}
      <UndoToast />
      {editable && platform === 'mobile' && (
        <EditorToolbar editor={editor} platform={platform} onPick={pick} />
      )}
      {editable && <BlockMenu editor={editor} />}
    </div>
  )
}

// packages/feature_base/moodiary_editor/editor/src/components/MoodiaryEditor.vue
<script setup lang="ts">
import { computed, nextTick, onBeforeUnmount, onMounted, ref, watch } from 'vue'
import { NodeSelection, type Transaction } from '@tiptap/pm/state'
import { EditorContent, useEditor } from '@tiptap/vue-3'
import { createEditorKit } from '../editor/tiptap'
import { bindApi, emitChange, markReady } from '../bridge'
import { post } from '../bridge/post'
import { links, meta } from '../bridge/meta'
import { bindScrollViewport } from '../bridge/scroll'
import { registerTitleFocus, title } from '../bridge/title'
import EditorToolbar from './EditorToolbar.vue'
import EditorSearchBar from './EditorSearchBar.vue'
import EditorMetaHeader from './EditorMetaHeader.vue'
import EditorLinksPanel from './EditorLinksPanel.vue'
import BlockMenu from './block/BlockMenu.vue'
import UndoToast from './ui/UndoToast.vue'
import { dismissKeyboard } from '../editor/keyboard'
import { openSearch } from '../editor/search'
import { useI18n } from 'vue-i18n'
import { wordCountOf } from '../editor/word-count'

const props = defineProps<{
  editable: boolean
  platform: 'mobile' | 'desktop'
}>()

const { t } = useI18n()

const editable = ref(props.editable)

const kit = createEditorKit({
  editable: props.editable,
  placeholder: t('content'),
  onChange: emitChange,
  onEditableChange: (value) => {
    editable.value = value
  },
})

const editor = useEditor({
  ...kit.options,
  onCreate: ({ editor: instance }) => {
    kit.attach(instance)
    bindApi(kit.api)
    markReady()
    instance.on('transaction', onViewportScroll)
    instance.on('transaction', onDocTransaction)
    wordCount.value = wordCountOf(instance.state.doc)
  },
})

const showToolbar = computed(() => editable.value)

const wordCount = ref(0)
function refreshWordCount(): void {
  const ed = editor.value
  wordCount.value = ed ? wordCountOf(ed.state.doc) : 0
}
function onDocTransaction({ transaction }: { transaction: Transaction }): void {
  if (transaction.docChanged && !editable.value) refreshWordCount()
}
watch(editable, (v) => {
  if (!v) refreshWordCount()
})

const showLinks = computed(
  () =>
    !editable.value &&
    links.value != null &&
    links.value.outgoing.length + links.value.incoming.length > 0,
)

const titleEl = ref<HTMLTextAreaElement>()
const viewportEl = ref<HTMLElement>()
let titleComposing = false
const titleVisible = computed(() => editable.value || title.value.trim().length > 0)
function autoGrowTitle(): void {
  const el = titleEl.value
  // v-show 隐藏时 scrollHeight 恒为 0，量出来会把 height 钉死成 0px
  if (!el || el.offsetParent === null) return
  el.style.height = 'auto'
  el.style.height = `${el.scrollHeight}px`
}
watch(title, (v) => {
  const el = titleEl.value
  if (el && el.value !== v) {
    el.value = v
    nextTick(autoGrowTitle)
  }
})
watch(titleVisible, (v) => {
  if (v) nextTick(autoGrowTitle)
})
function onTitleInput(e: Event): void {
  const el = e.target as HTMLTextAreaElement
  title.value = el.value
  autoGrowTitle()
  if (titleComposing) return
  post('titleChange', el.value)
}
function onTitleCompositionStart(): void {
  titleComposing = true
}
function onTitleCompositionEnd(e: Event): void {
  titleComposing = false
  const el = e.target as HTMLTextAreaElement
  title.value = el.value
  post('titleChange', el.value)
}
function onTitleKeydown(e: KeyboardEvent): void {
  if (e.key !== 'Enter' || e.isComposing) return
  e.preventDefault()
  editor.value?.commands.focus('start')
}
function onTitleFocus(): void {
  post('focusChange', 'title')
}
function onTitleBlur(): void {
  post('focusChange', '')
}

let activeHeadingIndex = -1
let spyRaf = 0
function computeActiveHeading(): void {
  const vp = viewportEl.value
  if (!vp) return
  const heads = vp.querySelectorAll<HTMLElement>(
    '.ProseMirror h1, .ProseMirror h2, .ProseMirror h3, .ProseMirror h4, .ProseMirror h5, .ProseMirror h6',
  )
  const vpTop = vp.getBoundingClientRect().top
  let active = heads.length > 0 ? 0 : -1
  heads.forEach((h, i) => {
    if (h.getBoundingClientRect().top - vpTop <= 12) active = i
  })
  if (active !== activeHeadingIndex) {
    activeHeadingIndex = active
    post('activeHeading', active)
  }
}
function onViewportScroll(): void {
  cancelAnimationFrame(spyRaf)
  spyRaf = requestAnimationFrame(computeActiveHeading)
}

function pick(type: string): void {
  dismissKeyboard()
  post(type)
}

let scrollRaf = 0
let viewportBottom = Infinity
function onViewportResize(): void {
  const ed = editor.value
  const vp = viewportEl.value
  if (!vp) return
  const bounds = vp.getBoundingClientRect()
  const bottomBefore = viewportBottom
  viewportBottom = bounds.bottom
  if (!ed || !ed.isEditable || !ed.isFocused) return
  const { selection } = ed.state
  const caret = ed.view.coordsAtPos(selection instanceof NodeSelection ? selection.from : selection.head)
  if (caret.bottom < bounds.top || caret.top > bottomBefore) return
  cancelAnimationFrame(scrollRaf)
  scrollRaf = requestAnimationFrame(() => ed.commands.scrollIntoView())
}
function onKeydown(e: KeyboardEvent): void {
  if ((e.metaKey || e.ctrlKey) && (e.key === 'f' || e.key === 'F')) {
    if (!editable.value) return
    e.preventDefault()
    openSearch()
  }
}
onMounted(() => {
  nextTick(autoGrowTitle)
  registerTitleFocus(() => titleEl.value?.focus())
  bindScrollViewport(viewportEl.value ?? null)
  viewportEl.value?.addEventListener('scroll', onViewportScroll, { passive: true })
  viewportBottom = viewportEl.value?.getBoundingClientRect().bottom ?? Infinity
  if (props.platform === 'mobile') window.addEventListener('resize', onViewportResize)
  window.addEventListener('keydown', onKeydown)
})
onBeforeUnmount(() => {
  registerTitleFocus(null)
  bindScrollViewport(null)
  viewportEl.value?.removeEventListener('scroll', onViewportScroll)
  window.removeEventListener('resize', onViewportResize)
  window.removeEventListener('keydown', onKeydown)
  cancelAnimationFrame(scrollRaf)
  cancelAnimationFrame(spyRaf)
})
</script>

<template>
  <div class="moodiary-editor-root" :data-platform="platform">
    <EditorToolbar
      v-if="editor && showToolbar && platform === 'desktop'"
      :editor="editor"
      :platform="platform"
      @pick="pick"
    />
    <EditorSearchBar v-if="platform === 'desktop'" :platform="platform" />
    <div class="moodiary-editor-scroll">
      <div ref="viewportEl" class="moodiary-editor-viewport">
        <EditorMetaHeader v-if="meta" :meta="meta" :editable="editable" :word-count="wordCount" />
        <textarea
          ref="titleEl"
          v-show="titleVisible"
          class="moodiary-title"
          rows="1"
          :readonly="!editable"
          :placeholder="editable ? t('titlePlaceholder') : ''"
          @input="onTitleInput"
          @compositionstart="onTitleCompositionStart"
          @compositionend="onTitleCompositionEnd"
          @keydown="onTitleKeydown"
          @focus="onTitleFocus"
          @blur="onTitleBlur"
        ></textarea>
        <EditorContent :editor="editor" class="moodiary-editor" />
        <EditorLinksPanel v-if="showLinks && links" :links="links" />
      </div>
    </div>
    <EditorSearchBar v-if="platform === 'mobile'" :platform="platform" />
    <UndoToast />
    <EditorToolbar
      v-if="editor && showToolbar && platform === 'mobile'"
      :editor="editor"
      :platform="platform"
      @pick="pick"
    />
    <BlockMenu v-if="editor && editable" :editor="editor" />
  </div>
</template>
