// packages/feature_base/moodiary_editor/editor/src/ui/toolbar/TableGridPicker.tsx
import { useState, type CSSProperties } from 'react'
import { cn } from 'cn'

const MAX_R = 8
const MAX_C = 8
const ROWS = Array.from({ length: MAX_R }, (_, i) => i + 1)
const COLS = Array.from({ length: MAX_C }, (_, i) => i + 1)

export default function TableGridPicker({
  className,
  style,
  onSelect,
}: {
  className?: string
  style?: CSSProperties
  onSelect: (rows: number, cols: number) => void
}) {
  const [hr, setHr] = useState(1)
  const [hc, setHc] = useState(1)

  return (
    <div
      className={cn('p-2', className)}
      style={style}
    >
      <div className="grid w-max gap-0.5" style={{ gridTemplateColumns: `repeat(${MAX_C}, 1.25rem)` }}>
        {ROWS.map((r) =>
          COLS.map((c) => (
            <button
              key={`${r}-${c}`}
              type="button"
              className={cn(
                'size-5 rounded-[3px] border',
                r <= hr && c <= hc ? 'border-primary bg-primary/40' : 'border-border',
              )}
              onMouseEnter={() => {
                setHr(r)
                setHc(c)
              }}
              onMouseDown={(e) => e.preventDefault()}
              onClick={() => onSelect(r, c)}
            />
          )),
        )}
      </div>
      <div className="mt-1.5 text-center text-xs text-muted-foreground tabular-nums">
        {hc} × {hr}
      </div>
    </div>
  )
}

// packages/feature_base/moodiary_editor/editor/src/components/TableGridPicker.vue
<script setup lang="ts">
import { ref } from 'vue'

const MAX_R = 8
const MAX_C = 8

const emit = defineEmits<{ (e: 'select', rows: number, cols: number): void }>()

const hr = ref(1)
const hc = ref(1)
</script>

<template>
  <div class="rounded-box border border-base-300 bg-base-100 p-2 shadow-lg">
    <div class="grid w-max gap-0.5" :style="{ gridTemplateColumns: `repeat(${MAX_C}, 1.25rem)` }">
      <template v-for="r in MAX_R" :key="r">
        <button
          v-for="c in MAX_C"
          :key="`${r}-${c}`"
          type="button"
          class="size-5 rounded-[3px] border"
          :class="r <= hr && c <= hc ? 'border-primary bg-primary/40' : 'border-base-300'"
          @mouseover="((hr = r), (hc = c))"
          @mousedown.prevent
          @click="emit('select', r, c)"
        />
      </template>
    </div>
    <div class="mt-1.5 text-center text-xs tabular-nums opacity-70">{{ hc }} × {{ hr }}</div>
  </div>
</template>
