// packages/feature_base/moodiary_editor/editor/src/components/nodes/ImageNodeView.tsx
import { useState } from 'react'
import { NodeViewWrapper, type NodeViewProps } from '@tiptap/react'
import BlockHandle from './BlockHandle'
import { blockMenu, openBlockMenu } from '../../editor/block-menu'
import { editable } from '../../editor/editable'
import { displaySrc } from '../../editor/media'
import { useStore } from '../../lib/store'

export default function ImageNodeView({ node, selected, getPos }: NodeViewProps) {
  const [owner] = useState(() => Symbol('image'))
  const menuOpen = useStore(blockMenu, (s) => s.owner === owner)
  const previewWidth = useStore(blockMenu, (s) => (s.owner === owner ? s.previewWidth : null))
  const canEdit = useStore(editable)

  const raw = node.attrs.src
  const src = typeof raw === 'string' ? displaySrc(raw) : ''
  const alt = (node.attrs.alt as string | null) ?? ''
  const title = (node.attrs.title as string | null) ?? undefined
  const v = node.attrs.widthPercent
  const widthPercent = typeof v === 'number' ? v : null
  const shown = previewWidth ?? widthPercent

  return (
    <NodeViewWrapper
      className={`moodiary-image${selected ? ' is-selected' : ''}${menuOpen ? ' is-menu-open' : ''}`}
      style={shown === null ? undefined : { maxWidth: `${shown}%` }}
      contentEditable={false}
    >
      <img
        className="moodiary-image__img moodiary-block__body"
        src={src}
        alt={alt}
        title={title}
        draggable={false}
      />
      {canEdit && (
        <BlockHandle
          variant="corner"
          onOpen={(anchor) => openBlockMenu({ owner, kind: 'image', anchor, getPos: () => getPos() })}
        />
      )}
    </NodeViewWrapper>
  )
}

// packages/feature_base/moodiary_editor/editor/src/components/nodes/ImageNodeView.vue
<script setup lang="ts">
import { computed } from 'vue'
import { NodeViewWrapper, nodeViewProps } from '@tiptap/vue-3'
import BlockHandle from './BlockHandle.vue'
import { blockMenu, openBlockMenu } from '../../editor/block-menu'
import { editable } from '../../editor/editable'
import { displaySrc } from '../../editor/media'

const props = defineProps(nodeViewProps)

const owner = Symbol('image')
const menuOpen = computed(() => blockMenu.owner === owner)

const src = computed(() => {
  const raw = props.node.attrs.src
  return typeof raw === 'string' ? displaySrc(raw) : ''
})
const alt = computed(() => (props.node.attrs.alt as string | null) ?? '')
const title = computed(() => (props.node.attrs.title as string | null) ?? undefined)

const widthPercent = computed(() => {
  const v = props.node.attrs.widthPercent
  return typeof v === 'number' ? v : null
})
const shown = computed(() =>
  menuOpen.value && blockMenu.previewWidth !== null ? blockMenu.previewWidth : widthPercent.value,
)

const wrapperStyle = computed(() =>
  shown.value === null ? undefined : { maxWidth: `${shown.value}%` },
)

function openMenu(anchor: HTMLElement): void {
  openBlockMenu({ owner, kind: 'image', anchor, getPos: () => props.getPos() })
}
</script>

<template>
  <NodeViewWrapper
    class="moodiary-image"
    :class="{ 'is-selected': selected, 'is-menu-open': menuOpen }"
    :style="wrapperStyle"
    contenteditable="false"
  >
    <img
      class="moodiary-image__img moodiary-block__body"
      :src="src"
      :alt="alt"
      :title="title"
      draggable="false"
    />
    <BlockHandle v-if="editable" variant="corner" @open="openMenu" />
  </NodeViewWrapper>
</template>
