// packages/feature_base/moodiary_editor/editor/src/components/nodes/AudioNodeView.vue
<script setup lang="ts">
import { computed, onMounted, ref } from 'vue'
import { NodeViewWrapper, nodeViewProps } from '@tiptap/vue-3'
import IconPlay from '~icons/lucide/play'
import IconPause from '~icons/lucide/pause'
import IconVolume from '~icons/lucide/volume-2'
import IconMuted from '~icons/lucide/volume-x'
import BlockHandle from './BlockHandle.vue'
import { blockMenu, openBlockMenu } from '../../editor/block-menu'
import { editable } from '../../editor/editable'
import { audioDefaultName, fetchMediaName, mediaUrl } from '../../editor/media'
import { formatTime, useMediaControls } from '../../editor/use-media'
import { useI18n } from 'vue-i18n'

const props = defineProps(nodeViewProps)

const { t } = useI18n()

const filename = computed(() => (props.node.attrs.filename as string | null) ?? '')
const src = computed(() => (filename.value ? mediaUrl(filename.value) : ''))

const displayName = ref(audioDefaultName())
onMounted(async () => {
  if (!filename.value) return
  const name = await fetchMediaName(filename.value)
  if (name) displayName.value = name
})

const owner = Symbol('audio')
const menuOpen = computed(() => blockMenu.owner === owner)
function openMenu(anchor: HTMLElement): void {
  openBlockMenu({ owner, kind: 'audio', anchor, getPos: () => props.getPos() })
}

const audioEl = ref<HTMLAudioElement | null>(null)
const { playing, duration, muted, sliderValue, toggle, toggleMute, onSeekInput, onSeekChange } =
  useMediaControls(audioEl)
</script>

<template>
  <NodeViewWrapper
    class="moodiary-media moodiary-media--audio"
    :class="{ 'is-selected': selected, 'is-menu-open': menuOpen }"
    contenteditable="false"
  >
    <div
      class="moodiary-block__body flex items-center gap-3 rounded-box border border-base-300 bg-base-200 px-3 py-2.5"
    >
      <button
        class="btn btn-circle btn-sm btn-primary shrink-0"
        type="button"
        :title="playing ? t('audio.pause') : t('audio.play')"
        @mousedown.prevent
        @click="toggle"
      >
        <component :is="playing ? IconPause : IconPlay" class="size-5" />
      </button>
      <div class="flex min-w-0 flex-1 flex-col gap-1">
        <div class="flex items-center gap-2">
          <span class="min-w-0 flex-1 truncate text-sm font-medium">{{ displayName }}</span>
          <button
            class="btn btn-circle btn-ghost btn-xs shrink-0"
            type="button"
            :title="muted ? t('audio.unmute') : t('audio.mute')"
            @mousedown.prevent
            @click="toggleMute"
          >
            <component :is="muted ? IconMuted : IconVolume" class="size-4" />
          </button>
          <BlockHandle v-if="editable" variant="inline" @open="openMenu" />
        </div>
        <div class="flex items-center gap-2">
          <input
            class="range range-primary range-xs flex-1"
            type="range"
            min="0"
            :max="duration || 0"
            step="any"
            :value="sliderValue"
            :aria-label="t('audio.progressLabel')"
            @input="onSeekInput"
            @change="onSeekChange"
          />
          <span class="shrink-0 text-xs tabular-nums opacity-70">
            {{ formatTime(sliderValue) }} / {{ formatTime(duration) }}
          </span>
        </div>
      </div>
    </div>
    <audio ref="audioEl" :src="src" preload="metadata"></audio>
  </NodeViewWrapper>
</template>

// packages/feature_base/moodiary_editor/editor/src/ui/nodes/AudioNodeView.tsx
import { useEffect, useRef, useState } from 'react'
import { NodeViewWrapper, type NodeViewProps } from '@tiptap/react'
import { Pause, Play, Volume2, VolumeX } from 'lucide-react'
import { cn } from 'cn'
import BlockHandle from './BlockHandle'
import { blockMenu, openBlockMenu } from '@/core/state/block-menu'
import { editable } from '@/core/state/editable'
import { fetchMediaName, mediaUrl } from '@/core/editor/media'
import { formatTime, useMediaControls } from '@/ui/hooks/use-media'
import { useT } from '@/core/i18n'
import { useStore } from '@/lib/store'
import { rangeClass } from '@/lib/range'
import { Button } from '@/ui/primitives/button'

export default function AudioNodeView({ node, selected, getPos }: NodeViewProps) {
  const t = useT()
  const [owner] = useState(() => Symbol('audio'))
  const menuOpen = useStore(blockMenu, (s) => s.owner === owner)
  const canEdit = useStore(editable)

  const filename = (node.attrs.filename as string | null) ?? ''
  const src = filename ? mediaUrl(filename) : undefined

  const [fetchedName, setFetchedName] = useState<string | null>(null)
  useEffect(() => {
    if (!filename) return
    let alive = true
    void fetchMediaName(filename).then((name) => {
      if (alive && name) setFetchedName(name)
    })
    return () => {
      alive = false
    }
  }, [filename])
  const displayName = fetchedName ?? t('audio.defaultName')

  const audioRef = useRef<HTMLAudioElement>(null)
  const { playing, duration, muted, sliderValue, toggle, toggleMute, seekTo, endSeek } =
    useMediaControls(audioRef)

  return (
    <NodeViewWrapper
      className={`moodiary-media moodiary-media--audio${selected ? ' is-selected' : ''}${menuOpen ? ' is-menu-open' : ''}`}
      contentEditable={false}
    >
      <div className="moodiary-block__body flex items-center gap-3 rounded-lg border border-border bg-muted px-3 py-2.5">
        <Button
          variant="default"
          size="icon"
          className="shrink-0 rounded-full"
          type="button"
          title={playing ? t('audio.pause') : t('audio.play')}
          onMouseDown={(e) => e.preventDefault()}
          onClick={toggle}
        >
          {playing ? <Pause className="size-5" /> : <Play className="size-5" />}
        </Button>
        <div className="flex min-w-0 flex-1 flex-col gap-1">
          <div className="flex items-center gap-2">
            <span className="min-w-0 flex-1 truncate text-sm font-medium">{displayName}</span>
            <Button
              variant="ghost"
              size="icon-xs"
              className="shrink-0 rounded-full"
              type="button"
              title={muted ? t('audio.unmute') : t('audio.mute')}
              onMouseDown={(e) => e.preventDefault()}
              onClick={toggleMute}
            >
              {muted ? <VolumeX className="size-4" /> : <Volume2 className="size-4" />}
            </Button>
            {canEdit && (
              <BlockHandle
                variant="inline"
                onOpen={(anchor) =>
                  openBlockMenu({ owner, kind: 'audio', anchor, getPos: () => getPos() })
                }
              />
            )}
          </div>
          <div className="flex items-center gap-2">
            <input
              className={cn(rangeClass, 'h-1.5 flex-1')}
              type="range"
              min={0}
              max={duration || 0}
              step="any"
              value={sliderValue}
              aria-label={t('audio.progressLabel')}
              onChange={(e) => seekTo(Number(e.currentTarget.value))}
              onPointerUp={(e) => endSeek(Number(e.currentTarget.value))}
              onPointerCancel={(e) => endSeek(Number(e.currentTarget.value))}
              onKeyUp={(e) => endSeek(Number(e.currentTarget.value))}
            />
            <span className="shrink-0 text-xs text-muted-foreground tabular-nums">
              {formatTime(sliderValue)} / {formatTime(duration)}
            </span>
          </div>
        </div>
      </div>
      <audio ref={audioRef} src={src} preload="metadata" />
    </NodeViewWrapper>
  )
}
