// packages/feature_base/moodiary_editor/editor/src/components/nodes/CodeBlockNodeView.vue
<script setup lang="ts">
import { computed, onBeforeUnmount, ref } from 'vue'
import { NodeViewContent, NodeViewWrapper, nodeViewProps } from '@tiptap/vue-3'
import IconCopy from '~icons/lucide/copy'
import IconCheck from '~icons/lucide/check'
import { useI18n } from 'vue-i18n'

const props = defineProps(nodeViewProps)

const { t } = useI18n()

const language = computed(() => {
  const l = props.node.attrs.language as string | null
  return l && l.length ? l : t('code.plainText')
})

const copied = ref(false)
let copiedTimer = 0
async function copy(): Promise<void> {
  const text = props.node.textContent
  try {
    await navigator.clipboard.writeText(text)
  } catch {
    const ta = document.createElement('textarea')
    ta.value = text
    ta.style.position = 'fixed'
    ta.style.opacity = '0'
    document.body.appendChild(ta)
    ta.select()
    try {
      document.execCommand('copy')
    } catch {
    }
    document.body.removeChild(ta)
  }
  copied.value = true
  clearTimeout(copiedTimer)
  copiedTimer = window.setTimeout(() => (copied.value = false), 1500)
}
onBeforeUnmount(() => clearTimeout(copiedTimer))
</script>

<template>
  <NodeViewWrapper class="moodiary-code-block">
    <div class="moodiary-code-block__head" contenteditable="false">
      <span class="moodiary-code-block__lang">{{ language }}</span>
      <button
        class="moodiary-code-block__copy"
        type="button"
        :title="copied ? t('code.copied') : t('code.copy')"
        @click="copy"
      >
        <component :is="copied ? IconCheck : IconCopy" class="size-4" />
        <span>{{ copied ? t('code.copied') : t('code.copy') }}</span>
      </button>
    </div>
    <!-- NodeViewContent 默认内联 white-space: pre-wrap，这里覆盖为 pre -->
    <pre><NodeViewContent as="code" style="white-space: pre" /></pre>
  </NodeViewWrapper>
</template>

// packages/feature_base/moodiary_editor/editor/src/ui/nodes/CodeBlockNodeView.tsx
import { useEffect, useRef, useState } from 'react'
import { NodeViewContent, NodeViewWrapper, type NodeViewProps } from '@tiptap/react'
import { Check, Copy } from 'lucide-react'
import { t } from '@/core/i18n'

export default function CodeBlockNodeView({ node }: NodeViewProps) {
  const l = node.attrs.language as string | null
  const language = l && l.length ? l : t('code.plainText')

  const [copied, setCopied] = useState(false)
  const timer = useRef(0)
  useEffect(() => () => clearTimeout(timer.current), [])

  async function copy(): Promise<void> {
    const text = node.textContent
    try {
      await navigator.clipboard.writeText(text)
    } catch {
      const ta = document.createElement('textarea')
      ta.value = text
      ta.style.position = 'fixed'
      ta.style.opacity = '0'
      document.body.appendChild(ta)
      ta.select()
      try {
        document.execCommand('copy')
      } catch {
      }
      document.body.removeChild(ta)
    }
    setCopied(true)
    clearTimeout(timer.current)
    timer.current = window.setTimeout(() => setCopied(false), 1500)
  }

  const Icon = copied ? Check : Copy
  return (
    <NodeViewWrapper className="moodiary-code-block">
      <div className="moodiary-code-block__head" contentEditable={false}>
        <span className="moodiary-code-block__lang">{language}</span>
        <button
          className="moodiary-code-block__copy"
          type="button"
          title={copied ? t('code.copied') : t('code.copy')}
          onMouseDown={(e) => e.preventDefault()}
          onClick={() => void copy()}
        >
          <Icon className="size-4" />
          <span>{copied ? t('code.copied') : t('code.copy')}</span>
        </button>
      </div>
      <pre>
        <NodeViewContent<'code'> as="code" style={{ whiteSpace: 'pre' }} />
      </pre>
    </NodeViewWrapper>
  )
}
