// packages/feature_base/moodiary_editor/editor/src/components/nodes/VideoNodeView.vue
<script setup lang="ts">
import { computed, onBeforeUnmount, onMounted, ref, watch } from 'vue'
import { NodeViewWrapper, nodeViewProps } from '@tiptap/vue-3'
import IconPlay from '~icons/lucide/play'
import IconPause from '~icons/lucide/pause'
import IconVolume from '~icons/lucide/volume-2'
import IconMuted from '~icons/lucide/volume-x'
import IconFullscreen from '~icons/lucide/maximize'
import BlockHandle from './BlockHandle.vue'
import { blockMenu, openBlockMenu } from '../../editor/block-menu'
import { editable } from '../../editor/editable'
import { post } from '../../bridge/post'
import { mediaUrl } from '../../editor/media'
import { formatTime, useMediaControls } from '../../editor/use-media'
import { useI18n } from 'vue-i18n'

const props = defineProps(nodeViewProps)

const { t } = useI18n()

const filename = computed(() => (props.node.attrs.filename as string | null) ?? '')
const src = computed(() => (filename.value ? mediaUrl(filename.value) : ''))

const owner = Symbol('video')
const menuOpen = computed(() => blockMenu.owner === owner)
const widthPercent = computed(() => {
  const v = props.node.attrs.widthPercent
  return typeof v === 'number' ? v : null
})
const shown = computed(() =>
  menuOpen.value && blockMenu.previewWidth !== null ? blockMenu.previewWidth : widthPercent.value,
)
const wrapperStyle = computed(() =>
  shown.value === null ? undefined : { maxWidth: `${shown.value}%` },
)
function openMenu(anchor: HTMLElement): void {
  openBlockMenu({ owner, kind: 'video', anchor, getPos: () => props.getPos() })
}
const poster = computed(() =>
  filename.value ? mediaUrl(filename.value, { poster: true }) : '',
)

const videoEl = ref<HTMLVideoElement | null>(null)
const { playing, duration, muted, sliderValue, dragging, toggle, toggleMute, seekTo, endSeek } =
  useMediaControls(videoEl)

const MIN_FRAME_RATIO = 4 / 5
const MAX_FRAME_RATIO = 16 / 9

const ratio = ref<number | null>(null)
const frameRatio = computed(() =>
  ratio.value === null
    ? MAX_FRAME_RATIO
    : Math.min(MAX_FRAME_RATIO, Math.max(MIN_FRAME_RATIO, ratio.value)),
)

const showBackdrop = computed(
  () =>
    poster.value !== '' &&
    (ratio.value === null || Math.abs(ratio.value - frameRatio.value) > 0.02),
)
function onLoadedMetadata(): void {
  const el = videoEl.value
  if (el && el.videoWidth > 0 && el.videoHeight > 0) {
    ratio.value = el.videoWidth / el.videoHeight
  }
}

const CONTROLS_HIDE_DELAY = 3000

const controlsVisible = ref(true)
let hideTimer: ReturnType<typeof setTimeout> | undefined

function clearHideTimer(): void {
  if (hideTimer !== undefined) {
    clearTimeout(hideTimer)
    hideTimer = undefined
  }
}
function keepControls(): void {
  controlsVisible.value = true
  clearHideTimer()
  if (playing.value) {
    hideTimer = setTimeout(() => {
      controlsVisible.value = false
    }, CONTROLS_HIDE_DELAY)
  }
}
function onPictureTap(): void {
  if (controlsVisible.value) {
    if (playing.value) {
      controlsVisible.value = false
      clearHideTimer()
    }
    return
  }
  keepControls()
}

watch(playing, keepControls)

function handOffToNative(): void {
  const el = videoEl.value
  if (!el || !filename.value) return
  try {
    el.pause()
  } catch {
  }
  keepControls()
  post('videoFullscreen', { name: filename.value, position: el.currentTime })
}

const trackEl = ref<HTMLElement | null>(null)

const progressPercent = computed(() => {
  const total = duration.value
  if (!(total > 0)) return 0
  return Math.min(100, Math.max(0, (sliderValue.value / total) * 100))
})

function timeAtPointer(e: PointerEvent): number | null {
  const el = trackEl.value
  const total = duration.value
  if (!el || !(total > 0)) return null
  const rect = el.getBoundingClientRect()
  if (rect.width <= 0) return null
  const fraction = Math.min(1, Math.max(0, (e.clientX - rect.left) / rect.width))
  return fraction * total
}

function onTrackDown(e: PointerEvent): void {
  const at = timeAtPointer(e)
  if (at === null) return
  // 老 WebView / jsdom 可能没有 setPointerCapture
  try {
    trackEl.value?.setPointerCapture?.(e.pointerId)
  } catch {
  }
  seekTo(at)
  keepControls()
}
function onTrackMove(e: PointerEvent): void {
  if (!dragging.value) return
  const at = timeAtPointer(e)
  if (at === null) return
  seekTo(at)
  keepControls()
}
function onTrackUp(e: PointerEvent): void {
  if (!dragging.value) return
  endSeek(timeAtPointer(e) ?? sliderValue.value)
  keepControls()
}

onMounted(() => {
  // iOS WKWebView 需要 playsinline 才能内联播放，否则弹系统全屏播放器
  const el = videoEl.value
  if (el) {
    el.setAttribute('playsinline', '')
    el.setAttribute('webkit-playsinline', '')
    el.addEventListener('loadedmetadata', onLoadedMetadata)
    onLoadedMetadata()
  }
})
onBeforeUnmount(() => {
  clearHideTimer()
  videoEl.value?.removeEventListener('loadedmetadata', onLoadedMetadata)
})
</script>

<template>
  <NodeViewWrapper
    class="moodiary-media moodiary-media--video"
    :class="{ 'is-selected': selected, 'is-menu-open': menuOpen }"
    :style="wrapperStyle"
    contenteditable="false"
  >
    <div
      class="moodiary-video__frame moodiary-video__frame--boxed moodiary-block__body rounded-box overflow-hidden"
      :style="{ '--video-ratio': frameRatio }"
    >
      <div
        v-if="showBackdrop"
        class="moodiary-video__backdrop"
        :style="{ backgroundImage: `url(${poster})` }"
      ></div>

      <video
        ref="videoEl"
        class="moodiary-video__el"
        :src="src"
        :poster="poster"
        preload="metadata"
        @mousedown.prevent
        @click="onPictureTap"
      ></video>

      <div
        class="moodiary-video__bar absolute inset-x-0 bottom-0 flex items-center gap-1"
        :class="{ 'is-hidden': !controlsVisible, 'is-scrubbing': dragging }"
        @mousedown.prevent
        @pointerdown="keepControls"
      >
        <button
          class="moodiary-video__key"
          type="button"
          :title="playing ? t('video.pause') : t('video.play')"
          @click="toggle"
        >
          <component :is="playing ? IconPause : IconPlay" class="size-5" />
        </button>

        <div
          ref="trackEl"
          class="moodiary-video__track"
          :class="{ 'is-pressed': dragging }"
          role="slider"
          :aria-label="t('video.progressLabel')"
          :aria-valuemin="0"
          :aria-valuemax="Math.round(duration)"
          :aria-valuenow="Math.round(sliderValue)"
          :aria-valuetext="`${formatTime(sliderValue)} / ${formatTime(duration)}`"
          @pointerdown="onTrackDown"
          @pointermove="onTrackMove"
          @pointerup="onTrackUp"
          @pointercancel="onTrackUp"
        >
          <span class="moodiary-video__rail"></span>
          <span class="moodiary-video__fill" :style="{ width: `${progressPercent}%` }"></span>
          <span class="moodiary-video__thumb" :style="{ left: `${progressPercent}%` }"></span>
        </div>

        <span class="moodiary-video__time">
          <span class="moodiary-video__time-pos">{{ formatTime(sliderValue) }}</span>
          <span class="moodiary-video__time-sep">/</span>
          <span class="moodiary-video__time-dur">{{ formatTime(duration) }}</span>
        </span>

        <button
          class="moodiary-video__key"
          type="button"
          :title="muted ? t('video.unmute') : t('video.mute')"
          @click="toggleMute"
        >
          <component :is="muted ? IconMuted : IconVolume" class="size-5" />
        </button>
        <button
          class="moodiary-video__key"
          type="button"
          :title="t('video.fullscreen')"
          @click="handOffToNative"
        >
          <IconFullscreen class="size-5" />
        </button>
      </div>

      <BlockHandle v-if="editable" variant="corner" @open="openMenu" />
    </div>
  </NodeViewWrapper>
</template>

// packages/feature_base/moodiary_editor/editor/src/ui/nodes/VideoNodeView.tsx
import { useEffect, useRef, useState, type CSSProperties, type PointerEvent } from 'react'
import { NodeViewWrapper, type NodeViewProps } from '@tiptap/react'
import { Maximize, Pause, Play, Volume2, VolumeX } from 'lucide-react'
import BlockHandle from './BlockHandle'
import { post } from '@/core/bridge/post'
import { blockMenu, openBlockMenu } from '@/core/state/block-menu'
import { editable } from '@/core/state/editable'
import { mediaUrl } from '@/core/editor/media'
import { formatTime, useMediaControls } from '@/ui/hooks/use-media'
import { useT } from '@/core/i18n'
import { useStore } from '@/lib/store'

const MIN_FRAME_RATIO = 4 / 5
const MAX_FRAME_RATIO = 16 / 9
const CONTROLS_HIDE_DELAY = 3000

export default function VideoNodeView({ node, selected, getPos }: NodeViewProps) {
  const t = useT()
  const [owner] = useState(() => Symbol('video'))
  const menuOpen = useStore(blockMenu, (s) => s.owner === owner)
  const previewWidth = useStore(blockMenu, (s) => (s.owner === owner ? s.previewWidth : null))
  const canEdit = useStore(editable)

  const filename = (node.attrs.filename as string | null) ?? ''
  const src = filename ? mediaUrl(filename) : undefined
  const poster = filename ? mediaUrl(filename, { poster: true }) : ''

  const v = node.attrs.widthPercent
  const widthPercent = typeof v === 'number' ? v : null
  const shown = previewWidth ?? widthPercent

  const videoRef = useRef<HTMLVideoElement>(null)
  const { playing, duration, muted, sliderValue, dragging, toggle, toggleMute, seekTo, endSeek } =
    useMediaControls(videoRef)

  const [ratio, setRatio] = useState<number | null>(null)
  const frameRatio =
    ratio === null ? MAX_FRAME_RATIO : Math.min(MAX_FRAME_RATIO, Math.max(MIN_FRAME_RATIO, ratio))
  const showBackdrop = poster !== '' && (ratio === null || Math.abs(ratio - frameRatio) > 0.02)

  function onLoadedMetadata(): void {
    const el = videoRef.current
    if (el && el.videoWidth > 0 && el.videoHeight > 0) setRatio(el.videoWidth / el.videoHeight)
  }

  const [controlsVisible, setControlsVisible] = useState(true)
  const hideTimer = useRef<ReturnType<typeof setTimeout>>(undefined)

  function clearHideTimer(): void {
    if (hideTimer.current !== undefined) {
      clearTimeout(hideTimer.current)
      hideTimer.current = undefined
    }
  }
  // play/pause 事件回调里 playing 还是上一帧的值，由调用方显式传入
  function keepControls(isPlaying = playing): void {
    setControlsVisible(true)
    clearHideTimer()
    if (isPlaying) {
      hideTimer.current = setTimeout(() => setControlsVisible(false), CONTROLS_HIDE_DELAY)
    }
  }
  function onPictureTap(): void {
    if (controlsVisible) {
      if (playing) {
        setControlsVisible(false)
        clearHideTimer()
      }
      return
    }
    keepControls()
  }
  useEffect(() => clearHideTimer, [])

  function handOffToNative(): void {
    const el = videoRef.current
    if (!el || !filename) return
    try {
      el.pause()
    } catch {
    }
    keepControls()
    post('videoFullscreen', { name: filename, position: el.currentTime })
  }

  const trackRef = useRef<HTMLDivElement>(null)
  const progressPercent =
    duration > 0 ? Math.min(100, Math.max(0, (sliderValue / duration) * 100)) : 0

  function timeAtPointer(e: PointerEvent): number | null {
    const el = trackRef.current
    if (!el || !(duration > 0)) return null
    const rect = el.getBoundingClientRect()
    if (rect.width <= 0) return null
    const fraction = Math.min(1, Math.max(0, (e.clientX - rect.left) / rect.width))
    return fraction * duration
  }
  function onTrackDown(e: PointerEvent): void {
    const at = timeAtPointer(e)
    if (at === null) return
    // 老 WebView / jsdom 可能没有 setPointerCapture
    try {
      trackRef.current?.setPointerCapture?.(e.pointerId)
    } catch {
    }
    seekTo(at)
    keepControls()
  }
  function onTrackMove(e: PointerEvent): void {
    if (!dragging) return
    const at = timeAtPointer(e)
    if (at === null) return
    seekTo(at)
    keepControls()
  }
  function onTrackUp(e: PointerEvent): void {
    if (!dragging) return
    endSeek(timeAtPointer(e) ?? sliderValue)
    keepControls()
  }

  return (
    <NodeViewWrapper
      className={`moodiary-media moodiary-media--video${selected ? ' is-selected' : ''}${menuOpen ? ' is-menu-open' : ''}`}
      style={shown === null ? undefined : { maxWidth: `${shown}%` }}
      contentEditable={false}
    >
      <div
        className="moodiary-video__frame moodiary-video__frame--boxed moodiary-block__body overflow-hidden rounded-lg"
        style={{ '--video-ratio': String(frameRatio) } as CSSProperties}
      >
        {showBackdrop && (
          <div className="moodiary-video__backdrop" style={{ backgroundImage: `url(${poster})` }} />
        )}

        {/* iOS WKWebView 需要 playsinline 才能内联播放，否则弹系统全屏播放器 */}
        <video
          ref={videoRef}
          className="moodiary-video__el"
          src={src}
          poster={poster}
          preload="metadata"
          playsInline
          webkit-playsinline=""
          onLoadedMetadata={onLoadedMetadata}
          onPlay={() => keepControls(true)}
          onPause={() => keepControls(false)}
          onEnded={() => keepControls(false)}
          onMouseDown={(e) => e.preventDefault()}
          onClick={onPictureTap}
        />

        <div
          className={`moodiary-video__bar absolute inset-x-0 bottom-0 flex items-center gap-1${controlsVisible ? '' : ' is-hidden'}${dragging ? ' is-scrubbing' : ''}`}
          onMouseDown={(e) => e.preventDefault()}
          onPointerDown={() => keepControls()}
        >
          <button
            className="moodiary-video__key"
            type="button"
            title={playing ? t('video.pause') : t('video.play')}
            onClick={toggle}
          >
            {playing ? <Pause className="size-5" /> : <Play className="size-5" />}
          </button>

          <div
            ref={trackRef}
            className={`moodiary-video__track${dragging ? ' is-pressed' : ''}`}
            role="slider"
            aria-label={t('video.progressLabel')}
            aria-valuemin={0}
            aria-valuemax={Math.round(duration)}
            aria-valuenow={Math.round(sliderValue)}
            aria-valuetext={`${formatTime(sliderValue)} / ${formatTime(duration)}`}
            onPointerDown={onTrackDown}
            onPointerMove={onTrackMove}
            onPointerUp={onTrackUp}
            onPointerCancel={onTrackUp}
          >
            <span className="moodiary-video__rail" />
            <span className="moodiary-video__fill" style={{ width: `${progressPercent}%` }} />
            <span className="moodiary-video__thumb" style={{ left: `${progressPercent}%` }} />
          </div>

          <span className="moodiary-video__time">
            <span className="moodiary-video__time-pos">{formatTime(sliderValue)}</span>
            <span className="moodiary-video__time-sep">/</span>
            <span className="moodiary-video__time-dur">{formatTime(duration)}</span>
          </span>

          <button
            className="moodiary-video__key"
            type="button"
            title={muted ? t('video.unmute') : t('video.mute')}
            onClick={toggleMute}
          >
            {muted ? <VolumeX className="size-5" /> : <Volume2 className="size-5" />}
          </button>
          <button
            className="moodiary-video__key"
            type="button"
            title={t('video.fullscreen')}
            onClick={handOffToNative}
          >
            <Maximize className="size-5" />
          </button>
        </div>

        {canEdit && (
          <BlockHandle
            variant="corner"
            onOpen={(anchor) =>
              openBlockMenu({ owner, kind: 'video', anchor, getPos: () => getPos() })
            }
          />
        )}
      </div>
    </NodeViewWrapper>
  )
}
