// packages/feature_base/moodiary_editor/editor/src/components/EditorLinksPanel.vue
<script setup lang="ts">
import { computed } from 'vue'
import { post } from '../bridge/post'
import type { EditorLinkItem, EditorLinks } from '../bridge/meta'
import IconLink from '~icons/lucide/link'
import IconWaypoints from '~icons/lucide/waypoints'
import IconArrowUpRight from '~icons/lucide/arrow-up-right'
import IconCornerDownLeft from '~icons/lucide/corner-down-left'
import IconChevronRight from '~icons/lucide/chevron-right'

const props = defineProps<{ links: EditorLinks }>()

const sections = computed(() => [
  { label: props.links.outgoingLabel, items: props.links.outgoing, outgoing: true },
  { label: props.links.incomingLabel, items: props.links.incoming, outgoing: false },
])

function onOpen(item: EditorLinkItem): void {
  post('linkTap', { id: item.id })
}
</script>

<template>
  <div class="links-panel card mx-4 my-6 bg-base-200">
    <div class="card-body gap-1 p-3 pl-3.5">
      <div class="flex items-center gap-2">
        <IconLink class="size-4 opacity-60" />
        <span class="text-sm font-semibold">{{ links.title }}</span>
        <span class="badge badge-sm badge-ghost">{{ links.outgoing.length + links.incoming.length }}</span>
        <span class="flex-1" />
        <button
          type="button"
          class="btn btn-ghost btn-sm btn-square"
          :title="links.graphTip"
          @mousedown.prevent
          @click="post('openGraph')"
        >
          <IconWaypoints class="size-5" />
        </button>
      </div>
      <template v-for="section in sections" :key="section.label">
        <template v-if="section.items.length">
          <div class="mt-2 px-1 text-xs opacity-60">{{ section.label }}</div>
          <ul class="list">
            <li v-for="item in section.items" :key="item.id">
              <button
                type="button"
                class="list-row w-full items-center rounded-field px-1 py-2 text-left active:bg-base-300"
                @mousedown.prevent
                @click="onOpen(item)"
              >
                <span
                  class="grid size-8 place-items-center rounded-full"
                  :class="section.outgoing ? 'bg-primary/15 text-primary' : 'bg-base-300'"
                >
                  <IconArrowUpRight v-if="section.outgoing" class="size-[18px]" />
                  <IconCornerDownLeft v-else class="size-[18px]" />
                </span>
                <span class="list-col-grow min-w-0">
                  <span class="block truncate text-sm font-medium">{{ item.title }}</span>
                  <span v-if="item.subtitle" class="block truncate text-xs opacity-60">{{ item.subtitle }}</span>
                </span>
                <IconChevronRight class="size-4 opacity-40" />
              </button>
            </li>
          </ul>
        </template>
      </template>
    </div>
  </div>
</template>

<style scoped>
.links-panel {
  flex: 0 0 auto;
  font-family: var(--app-font-sans);
}
</style>

// packages/feature_base/moodiary_editor/editor/src/ui/EditorLinksPanel.tsx
import { ArrowUpRight, ChevronRight, CornerDownLeft, Link, Waypoints } from 'lucide-react'
import { cn } from 'cn'
import type { EditorLinkItem, EditorLinks } from '@/core/state/meta'
import { post } from '@/core/bridge/post'
import { Badge } from '@/ui/primitives/badge'
import { Button } from '@/ui/primitives/button'

export default function EditorLinksPanel({ links }: { links: EditorLinks }) {
  const sections = [
    { label: links.outgoingLabel, items: links.outgoing, outgoing: true },
    { label: links.incomingLabel, items: links.incoming, outgoing: false },
  ]

  function onOpen(item: EditorLinkItem): void {
    post('linkTap', { id: item.id })
  }

  return (
    <div className="links-panel mx-4 my-6 flex-none rounded-lg bg-muted font-(family-name:--app-font-sans)">
      <div className="flex flex-col gap-1 p-3 pl-3.5">
        <div className="flex items-center gap-2">
          <Link className="size-4 text-muted-foreground" />
          <span className="text-sm font-semibold">{links.title}</span>
          <Badge variant="outline">{links.outgoing.length + links.incoming.length}</Badge>
          <span className="flex-1" />
          <Button
            variant="ghost"
            size="icon"
            title={links.graphTip}
            onMouseDown={(e) => e.preventDefault()}
            onClick={() => post('openGraph')}
          >
            <Waypoints className="size-5" />
          </Button>
        </div>
        {sections.map((section) =>
          section.items.length ? (
            <div key={section.label} className="contents">
              <div className="mt-2 px-1 text-xs text-muted-foreground">{section.label}</div>
              <ul className="flex flex-col">
                {section.items.map((item) => (
                  <li key={item.id}>
                    <button
                      type="button"
                      className="flex w-full items-center gap-3 rounded-md px-1 py-2 text-left active:bg-accent"
                      onMouseDown={(e) => e.preventDefault()}
                      onClick={() => onOpen(item)}
                    >
                      <span
                        className={cn(
                          'grid size-8 shrink-0 place-items-center rounded-full',
                          section.outgoing
                            ? 'bg-primary/15 text-primary'
                            : 'bg-accent text-accent-foreground',
                        )}
                      >
                        {section.outgoing ? (
                          <ArrowUpRight className="size-[18px]" />
                        ) : (
                          <CornerDownLeft className="size-[18px]" />
                        )}
                      </span>
                      <span className="min-w-0 flex-1">
                        <span className="block truncate text-sm font-medium">{item.title}</span>
                        {item.subtitle && (
                          <span className="block truncate text-xs text-muted-foreground">
                            {item.subtitle}
                          </span>
                        )}
                      </span>
                      <ChevronRight className="size-4 shrink-0 opacity-40" />
                    </button>
                  </li>
                ))}
              </ul>
            </div>
          ) : null,
        )}
      </div>
    </div>
  )
}
