// packages/feature_base/moodiary_editor/editor/src/components/EditorSearchBar.vue
<script setup lang="ts">
import { nextTick, onBeforeUnmount, ref, watch } from 'vue'
import { closeOverlay, openOverlay, type Overlay } from '../editor/overlay'
import {
  closeSearch,
  editorSearch,
  nextMatch,
  prevMatch,
  replaceAllMatches,
  replaceOne,
  setReplace,
  setTerm,
  toggleCase,
} from '../editor/search'
import IconUp from '~icons/lucide/chevron-up'
import IconDown from '~icons/lucide/chevron-down'
import IconClose from '~icons/lucide/x'
import { useI18n } from 'vue-i18n'

defineProps<{ platform: 'mobile' | 'desktop' }>()

const { t } = useI18n()

const findInput = ref<HTMLInputElement | null>(null)

const overlay: Overlay = { dismiss: () => closeSearch() }
onBeforeUnmount(() => closeOverlay(overlay))

watch(
  () => editorSearch.open,
  (open) => {
    if (open) openOverlay(overlay)
    else closeOverlay(overlay)
    if (open)
      nextTick(() => {
        findInput.value?.focus()
        findInput.value?.select()
      })
  },
)

function onFindKey(e: KeyboardEvent): void {
  if (e.key === 'Enter') {
    e.preventDefault()
    e.shiftKey ? prevMatch() : nextMatch()
  } else if (e.key === 'Escape') {
    e.preventDefault()
    closeSearch()
  }
}
</script>

<template>
  <div
    v-if="editorSearch.open"
    class="moodiary-search flex-none bg-base-100 px-2 py-1.5"
    :class="platform === 'desktop' ? 'border-b border-base-300' : 'border-t border-base-300'"
  >
    <div class="grid grid-cols-[1fr_auto] items-center gap-x-1.5 gap-y-1">
      <input
        ref="findInput"
        :value="editorSearch.term"
        type="text"
        :placeholder="t('search.findPlaceholder')"
        class="input input-xs w-full rounded-md"
        @input="setTerm(($event.target as HTMLInputElement).value)"
        @keydown="onFindKey"
      />
      <div class="flex items-center gap-0.5">
        <span class="min-w-[2.5rem] px-0.5 text-right text-xs tabular-nums opacity-60">
          {{ editorSearch.term ? `${editorSearch.current}/${editorSearch.count}` : '' }}
        </span>
        <button
          class="btn btn-ghost btn-xs btn-square rounded-md"
          :class="{ 'btn-active text-primary': editorSearch.caseSensitive }"
          type="button"
          :title="t('search.matchCase')"
          @mousedown.prevent
          @click="toggleCase"
        >
          <span class="text-[11px] font-bold">Aa</span>
        </button>
        <button class="btn btn-ghost btn-xs btn-square rounded-md" type="button" :title="t('search.previous')" @mousedown.prevent @click="prevMatch">
          <IconUp class="size-4" />
        </button>
        <button class="btn btn-ghost btn-xs btn-square rounded-md" type="button" :title="t('search.next')" @mousedown.prevent @click="nextMatch">
          <IconDown class="size-4" />
        </button>
        <button class="btn btn-ghost btn-xs btn-square rounded-md" type="button" :title="t('search.close')" @mousedown.prevent @click="closeSearch">
          <IconClose class="size-4" />
        </button>
      </div>

      <input
        :value="editorSearch.replace"
        type="text"
        :placeholder="t('search.replacePlaceholder')"
        class="input input-xs w-full rounded-md"
        @input="setReplace(($event.target as HTMLInputElement).value)"
      />
      <div class="flex items-center justify-end gap-0.5">
        <button class="btn btn-ghost btn-xs rounded-md" type="button" @mousedown.prevent @click="replaceOne">{{ t('search.replace') }}</button>
        <button class="btn btn-ghost btn-xs rounded-md" type="button" @mousedown.prevent @click="replaceAllMatches">{{ t('search.replaceAll') }}</button>
      </div>
    </div>
  </div>
</template>

// packages/feature_base/moodiary_editor/editor/src/ui/EditorSearchBar.tsx
import { useEffect, useRef, useState, type KeyboardEvent, type MouseEvent } from 'react'
import { ChevronDown, ChevronUp, X } from 'lucide-react'
import { cn } from 'cn'
import { closeOverlay, openOverlay, type Overlay } from '@/core/state/overlay'
import {
  closeSearch,
  editorSearch,
  nextMatch,
  prevMatch,
  replaceAllMatches,
  replaceOne,
  setReplace,
  setTerm,
  toggleCase,
} from '@/core/editor/search'
import { useT } from '@/core/i18n'
import { useStore } from '@/lib/store'
import { Button } from '@/ui/primitives/button'
import { Input } from '@/ui/primitives/input'

const prevent = (e: MouseEvent): void => e.preventDefault()

export default function EditorSearchBar({ platform }: { platform: 'mobile' | 'desktop' }) {
  const t = useT()
  const s = useStore(editorSearch)
  const findInput = useRef<HTMLInputElement>(null)
  const [overlay] = useState<Overlay>(() => ({ dismiss: () => closeSearch() }))

  useEffect(() => {
    if (!s.open) return
    openOverlay(overlay)
    findInput.current?.focus()
    findInput.current?.select()
    return () => closeOverlay(overlay)
  }, [s.open, overlay])

  function onFindKey(e: KeyboardEvent<HTMLInputElement>): void {
    if (e.key === 'Enter') {
      e.preventDefault()
      if (e.shiftKey) prevMatch()
      else nextMatch()
    } else if (e.key === 'Escape') {
      e.preventDefault()
      closeSearch()
    }
  }

  if (!s.open) return null
  return (
    <div
      className={cn(
        'moodiary-search flex-none bg-background px-2 py-1.5',
        platform === 'desktop' ? 'border-b border-border' : 'border-t border-border',
      )}
    >
      <div className="grid grid-cols-[1fr_auto] items-center gap-x-1.5 gap-y-1">
        <Input
          ref={findInput}
          value={s.term}
          type="text"
          placeholder={t('search.findPlaceholder')}
          className="h-7 rounded-md text-xs md:text-xs"
          onChange={(e) => setTerm(e.target.value)}
          onKeyDown={onFindKey}
        />
        <div className="flex items-center gap-0.5">
          <span className="min-w-[2.5rem] px-0.5 text-right text-xs text-muted-foreground tabular-nums">
            {s.term ? `${s.current}/${s.count}` : ''}
          </span>
          <Button
            variant="ghost"
            size="icon-xs"
            className={cn('rounded-md', s.caseSensitive && 'bg-accent text-primary')}
            title={t('search.matchCase')}
            onMouseDown={prevent}
            onClick={toggleCase}
          >
            <span className="text-[11px] font-bold">Aa</span>
          </Button>
          <Button
            variant="ghost"
            size="icon-xs"
            className="rounded-md"
            title={t('search.previous')}
            onMouseDown={prevent}
            onClick={prevMatch}
          >
            <ChevronUp className="size-4" />
          </Button>
          <Button
            variant="ghost"
            size="icon-xs"
            className="rounded-md"
            title={t('search.next')}
            onMouseDown={prevent}
            onClick={nextMatch}
          >
            <ChevronDown className="size-4" />
          </Button>
          <Button
            variant="ghost"
            size="icon-xs"
            className="rounded-md"
            title={t('search.close')}
            onMouseDown={prevent}
            onClick={closeSearch}
          >
            <X className="size-4" />
          </Button>
        </div>

        <Input
          value={s.replace}
          type="text"
          placeholder={t('search.replacePlaceholder')}
          className="h-7 rounded-md text-xs md:text-xs"
          onChange={(e) => setReplace(e.target.value)}
        />
        <div className="flex items-center justify-end gap-0.5">
          <Button variant="ghost" size="xs" className="rounded-md" onMouseDown={prevent} onClick={replaceOne}>
            {t('search.replace')}
          </Button>
          <Button variant="ghost" size="xs" className="rounded-md" onMouseDown={prevent} onClick={replaceAllMatches}>
            {t('search.replaceAll')}
          </Button>
        </div>
      </div>
    </div>
  )
}
