// packages/feature_base/moodiary_editor/editor/src/components/meta/WeatherPicker.vue
<script setup lang="ts">
import { ref } from 'vue'
import IconRefresh from '~icons/lucide/refresh-cw'
import IconX from '~icons/lucide/x'
import Popover from '../ui/Popover.vue'
import { post } from '../../bridge/post'
import type { EditorMeta } from '../../bridge/meta'
import { weatherGlyph } from './icons'
import { useI18n } from 'vue-i18n'

defineProps<{
  meta: EditorMeta
}>()

const { t } = useI18n()

const pop = ref<InstanceType<typeof Popover>>()

function act(type: string, payload?: unknown): void {
  pop.value?.close()
  post(type, payload)
}

defineExpose({ open: (anchor: HTMLElement) => pop.value?.open(anchor) })
</script>

<template>
  <Popover ref="pop" panel-class="w-[276px]" :label="t('meta.weather')">
    <div class="grid grid-cols-4 gap-0.5">
      <button
        v-for="w in meta.weatherOptions"
        :key="w.code"
        type="button"
        class="moodiary-pop-cell"
        :class="{ 'is-active': w.code === meta.weather?.icon }"
        :aria-pressed="w.code === meta.weather?.icon"
        @click="act('changeWeather', { code: w.code })"
      >
        <span class="moodiary-qi">{{ weatherGlyph(w.code) }}</span>
        <span>{{ w.label }}</span>
      </button>
    </div>
    <template v-if="meta.weatherAutoLabel || meta.weather">
      <div class="moodiary-pop-divider"></div>
      <button v-if="meta.weatherAutoLabel" type="button" class="moodiary-pop-item" @click="act('fetchWeather')">
        <IconRefresh />{{ meta.weatherAutoLabel }}
      </button>
      <button v-if="meta.weather" type="button" class="moodiary-pop-item is-dim" @click="act('clearWeather')">
        <IconX />{{ meta.weatherClearLabel }}
      </button>
    </template>
  </Popover>
</template>

// packages/feature_base/moodiary_editor/editor/src/ui/meta/WeatherPicker.tsx
import { useImperativeHandle, useRef, type Ref } from 'react'
import { RefreshCw, X } from 'lucide-react'
import Popover, { type PopoverHandle } from '@/ui/overlay/Popover'
import { post } from '@/core/bridge/post'
import type { EditorMeta } from '@/core/state/meta'
import { weatherGlyph } from './icons'
import type { PickerHandle } from './picker'
import { t } from '@/core/i18n'

export default function WeatherPicker({ ref, meta }: { ref?: Ref<PickerHandle>; meta: EditorMeta }) {
  const pop = useRef<PopoverHandle>(null)

  useImperativeHandle(ref, () => ({ open: (anchor) => pop.current?.open(anchor) }), [])

  function act(type: string, payload?: unknown): void {
    pop.current?.close()
    post(type, payload)
  }

  return (
    <Popover ref={pop} panelClass="w-[276px]" label={t('meta.weather')}>
      <div className="grid grid-cols-4 gap-0.5">
        {meta.weatherOptions.map((w) => {
          const active = w.code === meta.weather?.icon
          return (
            <button
              key={w.code}
              type="button"
              className={`moodiary-pop-cell${active ? ' is-active' : ''}`}
              aria-pressed={active}
              onClick={() => act('changeWeather', { code: w.code })}
            >
              <span className="moodiary-qi">{weatherGlyph(w.code)}</span>
              <span>{w.label}</span>
            </button>
          )
        })}
      </div>
      {(meta.weatherAutoLabel || meta.weather) && (
        <>
          <div className="moodiary-pop-divider"></div>
          {meta.weatherAutoLabel && (
            <button type="button" className="moodiary-pop-item" onClick={() => act('fetchWeather')}>
              <RefreshCw />
              {meta.weatherAutoLabel}
            </button>
          )}
          {meta.weather && (
            <button type="button" className="moodiary-pop-item is-dim" onClick={() => act('clearWeather')}>
              <X />
              {meta.weatherClearLabel}
            </button>
          )}
        </>
      )}
    </Popover>
  )
}
